# Generated by Django 3.0.3 on 2020-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='test',
            field=models.CharField(default='def', max_length=240),
        ),
    ]
