# Generated by Django 3.0.3 on 2020-04-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20200414_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='for_comment',
            new_name='for_user',
        ),
    ]
