# Generated by Django 3.0.3 on 2020-04-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_auto_20200415_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='follow',
            new_name='following',
        ),
    ]
