# Generated by Django 3.0.3 on 2020-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0014_auto_20200419_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/home/jay_rox/djp/level5/media/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
