# Generated by Django 3.0.3 on 2020-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0015_auto_20200419_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
