# Generated by Django 3.0.3 on 2020-04-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0016_auto_20200419_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='for_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='basicapp.Posts'),
        ),
    ]
